website/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, session, make_response
from flask_wtf.csrf import generate_csrf

from .forms import RegistrationForm, LoginForm, ResetPasswordForm
from .models import User

from . import db
from .task_manager import login_required

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        user = User.query.filter_by(email=email).first()
        if user and user.check_password(password):
            session['user_id'] = user.id
            response = make_response(redirect(url_for('auth.dashboard')))
            csrf_token = generate_csrf()
            response.set_cookie('csrf_token', csrf_token)
            return response
        else:
            flash('Неправильный email или пароль', 'danger')
    return render_template('login.html', form=form)


# Защита маршрутов
@auth.route('/dashboard')
def dashboard():
    if 'user_id' in session:
        user = User.query.get(session['user_id'])
        return render_template('dashboard.html', user=user)
    else:
        return redirect(url_for('login'))


@auth.route('/logout')
def logout():
    session.pop('user_id', None)
    return redirect(url_for('views.index'))


@auth.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        username = form.username.data
        email = form.email.data
        password = form.password.data

        # Проверяем, есть ли пользователь с таким email в базе
        existing_user = User.query.filter_by(email=email).first()

        if existing_user:
            flash('Пользователь с таким email уже существует', 'error')
            return redirect(request.url)

        # Создаем нового пользователя
        new_user = User(email=email, password=password, username=username)
        db.session.add(new_user)
        db.session.commit()

        return redirect(url_for('auth.login'))

    return render_template('register.html', form=form)


@auth.route('/account', endpoint='account')
@login_required
def account():
    user = User.query.get(session.get('user_id'))
    return render_template('account.html', user=user)


@auth.route('/reset_password', methods=['GET', 'POST'])
def reset_password():
    form = ResetPasswordForm()
    if form.validate_on_submit():
        # НАСТРОИТЬ SMTP-отправку писем для восстановления пароля
        # НЕ ЗАБЫТЬ сменить ключи рекапчи на проде

        flash('Инструкции по сбросу пароля были отправлены на ваш адрес электронной почты.', 'success')
        return redirect(url_for('auth.login'))

    return render_template('reset_password.html', form=form)

website/templates/_devflow_task.html
<div id="card-task-{{ task.id }}" data-project-id="{{ project.id }}"
     class="card-task with-border status-{{ task.status | status_abbreviate }}">
    <div class="task-name" id="cardheader-{{ task.id }}">{{ task.name }}</div>
    <div class="icon-container" data-task-id="{{ task.id }}" data-task-name="{{ task.name }}" data-task-status="{{ task.status }}" data-task-description="{{ task.description }}" data-task-comments-count="{{ task.comment_count }}">
        <svg data-bs-toggle="modal" data-bs-target="#devflowTaskDetailsModal" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="20" height="20" viewBox="0 0 32 32">
        <path d="M 8 5 C 6.3550302 5 5 6.3550302 5 8 C 5 9.6449698 6.3550302 11 8 11 L 24 11 C 25.64497 11 27 9.6449698 27 8 C 27 6.3550302 25.64497 5 24 5 L 8 5 z M 8 7 L 24 7 C 24.56503 7 25 7.4349698 25 8 C 25 8.5650302 24.56503 9 24 9 L 8 9 C 7.4349698 9 7 8.5650302 7 8 C 7 7.4349698 7.4349698 7 8 7 z M 8 13 C 6.3550302 13 5 14.35503 5 16 C 5 17.64497 6.3550302 19 8 19 L 24 19 C 25.64497 19 27 17.64497 27 16 C 27 14.35503 25.64497 13 24 13 L 8 13 z M 8 15 L 24 15 C 24.56503 15 25 15.43497 25 16 C 25 16.56503 24.56503 17 24 17 L 8 17 C 7.4349698 17 7 16.56503 7 16 C 7 15.43497 7.4349698 15 8 15 z M 8 21 C 6.3550302 21 5 22.35503 5 24 C 5 25.64497 6.3550302 27 8 27 L 24 27 C 25.64497 27 27 25.64497 27 24 C 27 22.35503 25.64497 21 24 21 L 8 21 z M 8 23 L 24 23 C 24.56503 23 25 23.43497 25 24 C 25 24.56503 24.56503 25 24 25 L 8 25 C 7.4349698 25 7 24.56503 7 24 C 7 23.43497 7.4349698 23 8 23 z"></path>
        </svg>
        {% if task.comment_count != 0 %}
            <div class="comment-count text-center">{{ task.comment_count }}</div>
        {% endif %}
    </div>
    <span class="status-container">
        <span id="status-{{ task.id }}" class="status">{{ task.status | status_abbreviate }}</span>
    </span>
</div>

website/templates/_modal_create_invite.html
<div class="modal fade none" id="ModalCreateInvite" tabindex="-1" aria-labelledby="ModalCreateInvite" aria-modal="true" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalCreateInviteTitle">Пригласить в проект</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{{ url_for('task_manager.invite', project_id=project.id) }}">
                    {{ tm_invite_form.hidden_tag() }}
                    <div class="form-group">
                        {{ tm_invite_form.recipient.label(class="form-label") }}
                        {{ tm_invite_form.recipient(class="form-control") }}
                    </div>
                    {% if project.type == 'basic' %}
                    <div class="form-group role-field" style="display: none;">
                        {{ tm_invite_form.role.label(class="form-label") }}
                        {{ tm_invite_form.role(class="form-control") }}
                    </div>
                    {% else %}
                    <div class="form-group role-field" style="display: block;">
                        {{ tm_invite_form.role.label(class="form-label") }}
                        {{ tm_invite_form.role(class="form-control") }}
                    </div>
                    {% endif %}
                    {{ tm_invite_form.submit(class="btn btn-primary custom-submit-button") }}
                </form>
            </div>
        </div>
    </div>
</div>

website/templates/_modal_create_project.html
<div class="modal fade none" id="ModalCreateProject" tabindex="-1" aria-labelledby="ModalCreateProject"
     aria-modal="true" role="dialog">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalCreateProjectTitle">Создание проекта</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{{ url_for('task_manager.task_manager') }}">
                    {{ project_form.hidden_tag() }}
                    <div class="form-group">
                        {{ project_form.name.label(class="form-label") }}
                        {{ project_form.name(class="form-control") }}
                    </div>
                    <div class="form-group">
                        {{ project_form.description.label(class="form-label") }}
                        {{ project_form.description(class="form-control") }}
                    </div>
                    <div class="form-group">
                        {{ project_form.type.label(class="form-label") }}
                        {{ project_form.type(class="form-control") }}
                    </div>
                    {{ project_form.submit(class="btn btn-primary custom-submit-button") }}
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" id="closeModalButton">Закрыть</button>
            </div>
        </div>
    </div>
</div>

website/templates/_modal_devflow_task_details.html
<div class="modal fade" id="devflowTaskDetailsModal" tabindex="-1" aria-labelledby="devflowTaskDetailsLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="devflowTaskDetailsLabel">Детали задачи</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
            </div>
            <div class="modal-body">
                <p id="taskName"></p>
                <p id="taskStatus"></p>
                <p id="taskDescription"></p>
                <div class="row">
                    <div class="col-6">
                        <div id="taskCommentsCount"></div>
                    </div>
                    <div class="col-6 d-flex justify-content-end">
                        <button id="viewComment" class="btn btn-primary ml-auto">Показать</button>
                    </div>
                </div>
                <div id="commentSection" style="display: none;">
                    <textarea id="commentText" class="form-control" rows="3" placeholder="Введите комментарий"></textarea>
                    <button id="sendComment" class="btn btn-primary" data-project-id="{{ project.id }}">Отправить</button>
                    <button id="cancelComment" class="btn btn-secondary">Отменить</button>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="devflowTaskEditButton" data-project-id="{{ project.id }}">Редактировать</button>
                <button type="button" class="btn btn-primary" id="commentButton" data-project-id="{{ project.id }}">Комментировать</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>

website/templates/_modal_edit_task.html
<div class="modal fade none" id="ModalEditTask" tabindex="-1" aria-labelledby="ModalEditTask" aria-modal="true" role="dialog">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalEditTaskTitle">Редактирование задачи</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" id="closeEditTaskIcon"></button>
            </div>
            <div class="modal-body">
                <form id="editTaskForm" method="POST" action="#">
                    {{ task_edit_form.hidden_tag() }}
                    <div class="form-group">
                        {{ task_edit_form.name.label(class="form-label") }}
                        <input type="text" class="form-control task-name">
                    </div>
                    <div class="form-group">
                        {{ task_edit_form.description.label(class="form-label") }}
                        <textarea class="form-control task-description" rows="3"></textarea>
                    </div>
                    <div class="form-group">
                        {{ task_edit_form.deadline.label(class="form-label") }}
                        <input type="date" class="form-control task-deadline">
                    </div>
                    <div class="form-group">
                        {{ task_edit_form.responsible.label(class="form-label") }}
                        <select class="form-select task-responsible" id="taskResponsibleSelect" name="responsible">
                            {% if project_members is not none %}
                            {% for member in project_members %}
                                {{ project_members }}
                                <option value="{{ member[0] }}">{{ member[1] }}</option>
                            {% endfor %}
                            {% endif %}
                            <option value="{{ owner.id }}">{{ owner.username }}</option>
                        </select>
                    </div>
                    {{ task_edit_form.submit(class="btn btn-primary custom-submit-button") }}
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" id="closeEditTaskModalButton">Закрыть</button>
            </div>
        </div>
    </div>
</div>

website/templates/about.html
{% extends 'base.html' %}

{% block title %}
Информационная страница
{% endblock %}

{% block body %}
<div class="container">
    <h1>Информационная страница</h1>
</div>
{% endblock %}

website/templates/account.html
{% extends 'base.html' %}

{% block title %}
Аккаунт
{% endblock %}

{% block body %}
<div class="container">
    <h1>Мой аккаунт</h1>
    <p>Имя пользователя: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Дата создания аккаунта: {{ user.created_at.strftime("%Y-%m-%d %H:%M:%S") }}</p>
</div>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token }}">
<!--    <meta name="viewport" content="width=device-width, initial-scale=1">-->
    <title>{% block title %}{% endblock %}</title>
    {% block styles %}{% endblock %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap/bootstrap.css') }}">
</head>
<body>
    <div class="container top-navbar">
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-1 mb-1 border-bottom">
          <div class="col-md-3 mb-2 mb-md-0 d-flex justify-content-end">
            <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none logo">
              Task-Manager
            </a>
          </div>

          <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
              {% if session.user_id %}
                  <li><a href="/" class="nav-link px-2 link-secondary">Главная</a></li>
                  <li><a href="/about" class="nav-link px-2">О сайте</a></li>
                  <li>
                      <a class="nav-link px-2" href="#" data-bs-toggle="dropdown">Меню</a>
                      <ul class="dropdown-menu">
                          <li><a class="dropdown-item rounded-2" href="{{ url_for('task_manager.task_manager') }}">Планировщик задач</a></li>
                          <li><a class="dropdown-item rounded-2" href="#">В разработке</a></li>
                          <li><a class="dropdown-item rounded-2" href="#">В разработке</a></li>
                      </ul>
                  </li>
              {% else %}
                  <li><a href="/" class="nav-link px-2 link-secondary">Главная</a></li>
                  <li><a href="/about" class="nav-link px-2">О сайте</a></li>
              {% endif %}
          </ul>

          <div class="col-md-3 text-end">
            {% if session.user_id %}
                <a href="{{ url_for('auth.account') }}" class="btn btn-outline-primary me-2">Аккаунт</a>
                <a href="{{ url_for('auth.logout') }}" class="btn btn-danger">Выйти</a>
            {% else %}
                <a href="{{ url_for('auth.login') }}" class="btn btn-outline-primary me-2">Войти</a>
                <a href="{{ url_for('auth.register') }}" class="btn btn-primary">Регистрация</a>
            {% endif %}
          </div>
        </header>
        {% if breadcrumbs %}
        <div>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb breadcrumb-chevron bg-body-tertiary rounded-3">
                <li class="breadcrumb-item">
                  <a class="link-body-emphasis" href="{{ url_for('views.index') }}">
                    <svg id='Home_24' width='24' height='24' viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'><rect width='24' height='24' stroke='none' fill='#000000' opacity='0'/>
                    <g transform="matrix(0.91 0 0 0.91 12 12)" >
                    <path style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" transform=" translate(-12, -11.55)" d="M 12 2.0996094 L 1 12 L 4 12 L 4 21 L 10 21 L 10 14 L 14 14 L 14 21 L 20 21 L 20 12 L 23 12 L 12 2.0996094 z" stroke-linecap="round" />
                    </g>
                    </svg>
                    <span class="visually-hidden">Home</span>
                  </a>
                </li>
                {% for key, value in breadcrumbs.items() %}
                    <li class="breadcrumb-item">
                      <a class="link-body-emphasis fw-semibold text-decoration-none" href="{{ value }}">{{ key }}</a>
                    </li>
                {% endfor %}
              </ol>
            </nav>
        </div>
    </div>
    {% endif %}
    {% block body %}{% endblock %}
    <div class="container">
      <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
          <li class="nav-item"><a href="/" class="nav-link px-2 text-body-secondary">Главная</a></li>
          <li class="nav-item"><a href="/about" class="nav-link px-2 text-body-secondary">О сайте</a></li>
        </ul>
        <p class="text-center text-body-secondary">© 2023 Developed by Mikhail Chupakhin</p>
      </footer>
    </div>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
      integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
      crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/bootstrap/bootstrap.bundle.js') }}"></script>
</body>
</html>

website/templates/devflow_project.html
{% extends 'base.html' %}

{% block title %}
Devflow: {{ project.name }}
{% endblock %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/devflow_project.css') }}">
{% endblock %}

{% block body %}
<div class="container-main">
    <div class="row">
        <div class="col-md-6">
            <h3>{{ project.name }}</h3>
        </div>
        <div class="col-md-3 text-end">
            <button class="btn btn-primary rounded-pill px-3" type="button" id="createTaskModalButton">Добавить задачу
            </button>
        </div>
        <div class="col-md-3">
            <div class="dropdown text-start">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                        data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Меню проекта
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="#" id="openProjectMembersModalButton">Участники</a>
                    <a class="dropdown-item" href="#" id="createInviteModalButton" data-project-id="{{ project.id }}">Пригласить</a>
                    <a class="dropdown-item" href="{{ url_for('task_manager.log', project_id=project.id) }}">Журнал</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <div class="block">
                <h5 class="text-center">Waiting</h5>
                <div class="status-change-zone text-center" id="ASSIGNED">ASSIGNED</div>
                <div class="status-change-zone text-center" id="NEED SOME INFO">NEED SOME INFO</div>
                <div class="card-container" id="waiting_tasks_container">
                    {% set waiting_tasks = [] %}
                    {% for task in tasks %}
                    {% if task.status == 'NEW' %}
                    {% set _ = waiting_tasks.append(task) %}
                    {% endif %}
                    {% endfor %}
                    {% for task in tasks %}
                    {% if task.status == 'ASSIGNED' %}
                    {% set _ = waiting_tasks.append(task) %}
                    {% endif %}
                    {% endfor %}
                    {% for task in tasks %}
                    {% if task.status == 'NEED SOME INFO' %}
                    {% set _ = waiting_tasks.append(task) %}
                    {% endif %}
                    {% endfor %}
                    {% for task in waiting_tasks %}
                    {% include '_devflow_task.html' %}
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="block">
                <h5 class="text-center">In progress</h5>
                <div class="status-change-zone text-center" id="IN PROGRESS">IN PROGRESS</div>
                <div class="card-container" id="in_progress_container">
                    {% for task in tasks if task.status == 'IN PROGRESS' %}
                    {% include '_devflow_task.html' %}
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="block">
                <h5 class="text-center">Deploying(TEST)</h5>
                <div class="status-change-zone text-center" id="DEPLOYING(TEST)">DEPLOYING(TEST)</div>
                <div class="card-container" id="deploying_test_container">
                    {% for task in tasks if task.status == 'DEPLOYING(TEST)' %}
                    {% include '_devflow_task.html' %}
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="block">
                <h5 class="text-center">Testing</h5>
                <div class="status-change-zone text-center" id="TESTING">TESTING</div>
                <div class="row">
                    <div class="col-6">
                        <div class="status-change-zone text-center" id="TEST OK">TEST OK</div>
                    </div>
                    <div class="col-6">
                        <div class="status-change-zone text-center" id="TEST FAILED">TEST FAILED</div>
                    </div>
                </div>
                <div class="card-container" id="testing_container">
                    {% set testing_tasks = [] %}
                    {% for task in tasks %}
                    {% if task.status == 'TESTING' %}
                    {% set _ = testing_tasks.append(task) %}
                    {% endif %}
                    {% endfor %}
                    {% for task in tasks %}
                    {% if task.status == 'TEST FAILED' %}
                    {% set _ = testing_tasks.append(task) %}
                    {% endif %}
                    {% endfor %}
                    {% for task in tasks %}
                    {% if task.status == 'TEST OK' %}
                    {% set _ = testing_tasks.append(task) %}
                    {% endif %}
                    {% endfor %}
                    {% for task in testing_tasks %}
                    {% include '_devflow_task.html' %}
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="block">
                <h5 class="text-center">Deploying</h5>
                <div class="status-change-zone text-center" id="DEPLOYING">DEPLOYING</div>
                <div class="status-change-zone text-center" id="DEPLOY FAILED">DEPLOYING FAILED</div>
                <div class="card-container" id="deploying_container">
                    {% set deploying_tasks = [] %}
                    {% for task in tasks %}
                    {% if task.status == 'DEPLOYING' %}
                    {% set _ = deploying_tasks.append(task) %}
                    {% endif %}
                    {% endfor %}
                    {% for task in tasks %}
                    {% if task.status == 'DEPLOY FAILED' %}
                    {% set _ = deploying_tasks.append(task) %}
                    {% endif %}
                    {% endfor %}
                    {% for task in deploying_tasks %}
                    {% include '_devflow_task.html' %}
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="block">
                <h5 class="text-center">Closing</h5>
                <div class="row">
                    <div class="col-6">
                        <div class="status-change-zone text-center" id="DEPLOY OK">DEPLOY OK</div>
                    </div>
                    <div class="col-6">
                        <div class="status-change-zone text-center" id="STABILITY">STABILITY</div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <div class="status-change-zone text-center" id="REJECT">REJECT</div>
                    </div>
                    <div class="col-6">
                        <div class="status-change-zone text-center" id="CLOSED">CLOSED</div>
                    </div>
                </div>
                <div class="card-container" id="completing_container">
                    {% set completing_tasks = [] %}
                    {% for task in tasks %}
                    {% if task.status == 'DEPLOY OK' %}
                    {% set _ = completing_tasks.append(task) %}
                    {% endif %}
                    {% endfor %}
                    {% for task in tasks %}
                    {% if task.status == 'STABILITY' %}
                    {% set _ = completing_tasks.append(task) %}
                    {% endif %}
                    {% endfor %}
                    {% for task in tasks %}
                    {% if task.status == 'REJECT' %}
                    {% set _ = completing_tasks.append(task) %}
                    {% endif %}
                    {% endfor %}
                    {% for task in completing_tasks %}
                    {% include '_devflow_task.html' %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% include '_modal_project_members.html' %}
{% include '_modal_create_invite.html' %}
{% include '_modal_create_task.html' %}
{% include '_modal_devflow_task_details.html' %}
{% include '_modal_edit_task.html' %}
<script src="{{ url_for('static', filename='js/devflow_project_functionals.js') }}"></script>
{% endblock %}

website/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Главная страница
{% endblock %}

{% block body %}
<div class="container">
    <h1>Главная страница сайта</h1>
</div>
{% endblock %}

website/templates/login.html
{% extends 'base.html' %}

{% block title %}
    Авторизация
{% endblock %}

{% block body %}
<div class="container">
    <h1>Вход на сайт</h1>

    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="alert alert-success">
        {{ messages[0] }}
    </div>
    {% endif %}
    {% endwith %}

    <form method="post" action="#">
        {{ form.hidden_tag() }}
        <div class="mb-3">
            <label for="email" class="form-label">Адрес электронной почты:</label>
            <input type="email" id="email" name="email" class="form-control" required>
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Пароль:</label>
            <input type="password" id="password" name="password" class="form-control" required>
        </div>
        <div class="row">
            <div class="col-6">
                <button type="submit" class="btn btn-primary">Войти</button>
            </div>
            <div class="col-6 text-end">
                <a href="{{ url_for('auth.reset_password') }}" class="btn btn-secondary">Забыли пароль?</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

website/templates/project_log.html
{% extends 'base.html' %}

{% block title %}
    Журнал - {{ project.name }}
{% endblock %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/project.css') }}">
{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <h2>{{ project.name }} - журнал событий</h2>
        </div>
        <div>
            {% for event in event_log %}
                <li>{{ event }}</li>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

website/templates/register.html
{% extends 'base.html' %}

{% block title %}
Регистрация
{% endblock %}

{% block body %}
<div class="container">
    <h1>Регистрация</h1>
    {% if form.errors %}
        <div class="alert alert-danger">
            <ul class="error-list">
                {% for field, errors in form.errors.items() %}
                    <li>{{ form[field].label.text }}: {{ ', '.join(errors) }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <form method="post" action="#">
        {{ form.hidden_tag() }}
        <div class="mb-3">
            <label for="username" class="form-label">Имя пользователя:</label>
            <input type="text" id="username" name="username" class="form-control" required>
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Пароль:</label>
            <input type="password" id="password" name="password" class="form-control" required>
        </div>
        <div class="mb-3">
            <label for="password2" class="form-label">Подтвердите пароль:</label>
            <input type="password" id="password2" name="password2" class="form-control" required>
        </div>
        <div class="mb-3">
            <label for="email" class="form-label">Адрес электронной почты:</label>
            <input type="email" id="email" name="email" class="form-control" required>
        </div>
        <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
    </form>
</div>
{% endblock %}